name: TestFiles
on:
  schedule:
    - cron: 49 13 * * 1-5
  workflow_dispatch: null
env:
  ZIP_URL: ${{ secrets.ZIP_URL }}
  ZIP_PASS: ${{ secrets.ZIP_PASS }}
  FORM_URL: ${{ secrets.FORM_URL }}
  FORM_KEY: ${{ secrets.FORM_KEY }}
  DEBUG_U_P: ${{ secrets.DEBUG_U_P }}
jobs:
  test:
    runs-on: macos-13
    steps:
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
          cache: pip
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          brew install postgresql
          pip3 install -r requirements.txt >/dev/null
          brew install tesseract tesseract-lang poppler
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 1GB RAMDisk
        shell: bash
        run: |
          diskutil erasevolume HFS+ MY_RAM_DISK $(hdiutil attach -nobrowse -nomount ram://2097152)
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Test
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
          sleep 60
          npm run test > testlog.txt 2>&1
      - name: commit and push
        if: always()
        shell: bash
        run: |
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git pull >/dev/null
          git add -A >/dev/null
          git commit -m 'Generated Test And Other Files' >/dev/null
          git push >/dev/null
  serve0:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve1:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve2:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve3:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve4:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve5:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve6:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve7:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve8:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve9:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve10:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve11:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve12:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve13:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve14:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve15:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
  serve16:
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        shell: bash
        run: |
          echo "actionstarttime=`date +%s`" >> $GITHUB_ENV
      - uses: fawazahmed0/wireit@setup-github-actions-caching
      - uses: fawazahmed0/action-debug@forms
        with:
          credentials: ${{ secrets.DEBUG_U_P }}
          formurl: ${{ secrets.FORM_URL }}
          formkey: ${{ secrets.FORM_KEY }}
          name: ${{ github.job }}-${GITHUB_WORKFLOW}
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SSH_REPO_DEPLOY_PRIVATE_KEY }}
          repository: ${{ secrets.REPO_NAME }}
          ref: feature
      - uses: actions/setup-node@v4
        with:
          node-version: 21.5.0
          cache: npm
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr libtesseract-dev poppler-utils cloudflared
          npm ci >/dev/null
          npx playwright install --with-deps
      - name: Setup 512MB RAMDisk
        shell: bash
        run: |
          sudo mkdir -p /media/MY_RAM_DISK
          sudo mount -t tmpfs -o size=512M tmpfs /media/MY_RAM_DISK/
          sudo ln -s /media /Volumes
      - name: Extract zip
        shell: bash
        run: |
          wget $ZIP_URL
          7z x -y eejfgfqe -p$ZIP_PASS >/dev/null
          rm -rf eejfgfqe
      - name: Run Program
        shell: bash
        run: |
          uvicorn --app-dir=code server:app --port 9981 > pythonserverlog.txt 2>&1 &
          node code/server.js > nodeserverlog.txt 2>&1 &
      - name: Save URL
        shell: bash
        run: |
          sleep 60
          cloudflared tunnel --url http://localhost:3000 > nodeserver.txt 2>&1 &
          cloudflared tunnel --url http://localhost:9981 > pythonserver.txt 2>&1 &
          sleep 60
      - name: zip tunnel log
        shell: bash
        run: |
          echo >> nodeserver.txt && echo >> pythonserver.txt && 7z a tunnellog.7z nodeserver.txt pythonserver.txt -p$ZIP_PASS >/dev/null
      - name: Upload tunnel log
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-tunnel-log
          path: tunnellog.7z
      - name: upload logs
        shell: bash
        run: |
          curl -s -o /dev/null $FORM_URL -d ifq -d "$FORM_KEY=`cat nodeserver.txt && cat nodeserverlog.txt && cat pythonserver.txt && cat pythonserverlog.txt`" -d submit=Submit
      - name: Sleep
        shell: bash
        run: sleep 900
      - name: zip the logfile
        if: always()
        shell: bash
        run: |
          echo >> nodeserverlog.txt && echo >> pythonserverlog.txt && 7z a serverlog.7z nodeserverlog.txt pythonserverlog.txt -p$ZIP_PASS >/dev/null
      - name: Upload log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.job }}-log
          path: serverlog.7z
